### ISSUE TITLE
User can view what's currently in the store

### ISSUE THREAD

**Issue by le-andre** [le-andre/ajax-project#1]
## ⚙️Motivation
User will be able to view current items in the cosmetic store for Fortnite

## 📐 Functionality

Create a responsive page that displays an image with a title, icon and description for how much an item costs.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/103016667/173637566-7e200a75-db4b-468e-8261-14767607e5ae.png)
![image](https://user-images.githubusercontent.com/103016667/173637621-038f0b19-c3d9-4763-b165-d82366cbfef1.png)

## ✅ Task List

> #####

- [x] Add a div[data-view="featured-items"] to the HTML
- [x] Add a header that indicates the page is for the Featured of the current week
- [x] Add a Navbar that includes four clickable text to view-swap into and from.
- [x] Add a tracker for the current week
- [x] Create a countdown timer in an hour:minute:seconds format to see when the shop will update next.
- [x] Create an empty UL in the HTML, and fill it with "dummy data"
  - [x] After contents in UL is formatted correctly, create a function to create the contents in the UL as a DOM Tree, and append it to the UL.
  - [x] Remove "dummy HTML data"
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
